vich_uploader:
  db_driver: orm # or mongodb or phpcr

  mappings:
    product_image:
      uri_prefix: /var/pictures
      upload_destination: '%kernel.project_dir%/var/pictures'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
